version: '3.8'
services:
  antonioyosica-website:
    container_name: antonioyosica-website
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./config/Dockerfile
    image: antonioyosica/website:latest
    ports:
      - 3000:3000
    networks:
      - nginx-proxymanager_default
networks:
  nginx-proxymanager_default:
    external: true
